services:
  - type: web
    name: rideflow-mobility
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        value: mongodb://kaviniyaa05_db_user:kavi123456@ac-caxcvf8-shard-00-00.x6rov7b.mongodb.net:27017,ac-caxcvf8-shard-00-01.x6rov7b.mongodb.net:27017,ac-caxcvf8-shard-00-02.x6rov7b.mongodb.net:27017/rideflow?tls=true&authSource=admin&retryWrites=true&w=majority
      - key: EMAIL_USER
        value: rideflow2026@gmail.com
      - key: EMAIL_PASS
        value: tppr qgea mdht smjg
