services:
  - type: web
    name: rideflow-mobility
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        value: mongodb+srv://kaviniyaa05_db_user:kavi123456@cluster0.x6rov7b.mongodb.net/rideflow?authSource=admin&retryWrites=true&w=majority&appName=Cluster0
      - key: EMAIL_USER
        value: rideflow2026@gmail.com
